

all:

check:
	 mypy --html-report out-mypy  \
	 --config-file mypy.ini \
	 		duckietown-challenges/src/duckietown_challenges \
			duckietown-challenges-server/src/duckietown_challenges_server \
			duckietown-build-utils/src/duckietown_build_utils \
			duckietown-docker-utils/src/duckietown_docker_utils \
			duckietown-tokens/src/duckietown_tokens